// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  blaze: string;
  bug: string;
  fire: string;
  flying: string;
  grass: string;
  img: string;
  poison: string;
  pokemonData: string;
  root: string;
  statCircle: string;
  statName: string;
  stats: string;
  type: string;
  types: string;
  water: string;
}
export const cssExports: CssExports;
export default cssExports;
