// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  layout: string;
  loading: string;
  loadingBall: string;
  pokemons: string;
  root: string;
  searchFilter: string;
  searchInput: string;
}
export const cssExports: CssExports;
export default cssExports;
